name: Run cron

on:
  push:
  schedule:
    - cron: "13 22 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn
      - name: Run script
        run: yarn e2e
        env:
          SECRET_TEST_MESSAGE: ${{ secrets.SECRET_TEST_MESSAGE }}
